name: Test

on:
  pull_request

jobs:
  pull_request:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y yajl-tools ffmpeg libsm6 libxext6 libxml2-dev libxslt-dev
      - name: Setup Python Version
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - name: Run tests
        run: CONCURRENCY=4 LOG_LEVEL=INFO make test
