name: Test

on:
  pull_request

jobs:
  pull_request:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y yajl-tools ffmpeg libsm6 libxext6 libxml2-dev libxslt-dev
      - name: Setup Python Version
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - name: Run tests
        run: CONCURRENCY=4 LOG_LEVEL=INFO make test
